#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/rest_docs
#    username: root
#    password: 120512zxc@
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        ddl-auto: update
#        show_sql: true
#        format_sql: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/Toy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        logging.level:
          org.hibernate.SQL: debug
        #  org.hibernate.type: trace


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
mvc:
  path match:
    matching-strategy: ant_path_matcher
