spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/RestDocs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
