spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_docs
    username: root
    password: 120512zxc@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
